server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.1.170:3100/loki/api/v1/push

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: [localhost]
        labels:
          job: traefik
          service: traefik
          __path__: /var/log/traefik/traefik.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+)\s+(?P<level>\w+)'
      - labels:
          level:

  - job_name: traefik-access
    static_configs:
      - targets: [localhost]
        labels:
          job: traefik-access
          service: traefik
          __path__: /var/log/traefik/access.log
    pipeline_stages:
      - json:
          expressions:
            status: OriginStatus
            method: RequestMethod
            path: RequestPath
            host: RequestHost
            duration: Duration
      - labels:
          status:
          method:
          host:
