http:
  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
  services:
    adguard-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.253:80
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    adguard-2-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.224:80
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    birdnet-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.80:8080
        healthCheck:
          path: /
          interval: 30s
          timeout: 10s
    homeassistant-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.155:8123
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    influx-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.56:8086
        healthCheck:
          path: /ping
          interval: 30s
          timeout: 5s
    kea-1-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.133:8000
    kea-2-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.134:8000
    myspeed-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.152:5216
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    omada-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.47:8043
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    pairdrop-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.97:3000
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    proxmox-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.137:8006
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    proxmox2-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.125:8006
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    proxmox3-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.126:8006
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    pulse-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.122:7655
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    stork-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.234:8080
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    watchyourlan-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.195:8840
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    wiki-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.135:3000
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    esphome-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.169:6052
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    z2m-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.228:8099
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    zwave-js-ui-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.141:8091
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    truenas-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.98:443
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    caddy-service:
      loadBalancer:
        servers:
        - url: http://localhost:2019
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
    uptime-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.132:3001
        healthCheck:
          path: /
          interval: 30s
          timeout: 5s
